### ISSUE TITLE
can not generate the *.entrypoint file

### ISSUE THREAD

**Issue by Dfault0** [gaojun0816/nativedisclosurer#3]
helllo, i meet a problem and i could not solve it. why this happens?
the environment is :
- Ubuntu 2022.04
- python version 3.7.7 or 3.8.10
- the java version is: 1.8.0
 i can generate the “_result” folder (.dot .result performance .map) successful 
but only can generate them.
![捕获2](https://user-images.githubusercontent.com/24689346/219257096-3c9eed07-b4be-44c5-b548-8ea7e66c0fb9.PNG)

the result is ncomplete .
![result](https://user-images.githubusercontent.com/24689346/219257735-1e6887a0-bf36-4abb-801b-3952995887c2.PNG)

Did I do something wrong？
I would appreciate it if you could reply my question.

**Comment by reach-the-peak** [comment]
Did you solve it?

**Comment by Dfault0** [comment]
yes,i solved it. thanks for your reply.




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月27日(星期四) 晚上6:26
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gaojun0816/nativediscloser] can not generate the *.entrypoint file (Issue #3)





 
Did you solve it?

**Comment by reach-the-peak** [comment]
Hello, I am not the author, I also encountered the same problem, I would like to ask you

**Comment by reach-the-peak** [comment]
How did you solve it

**Comment by Dfault0** [comment]
I encountered this problem when I use Jucify. you can read this issue carefully ("https://github.com/JordanSamhi/JuCify/issues/9").




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2023年4月27日(星期四) 晚上6:34
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [gaojun0816/nativediscloser] can not generate the *.entrypoint file (Issue #3)





 
Hello, I am not the author, I also encountered the same problem, I would like to ask you

**Comment by Dfault0** [comment]
> How did you solve it
i checkout 6897c58,then solved it.

**Comment by reach-the-peak** [comment]
Have you tested your own apk, can you analyze the results

**Comment by Dfault0** [comment]
> Have you tested your own apk, can you analyze the results

yes
